FROM eclipse-temurin:17

LABEL mentainer="rahulghadage1310@gmail.com"

WORKDIR /app

COPY target/SpringBoot-Application-0.0.1-SNAPSHOT.jar  /app/springboot-application.jar

ENTRYPOINT [ "java","-jar","springboot-application.jar" ]